### ISSUE TITLE
[EPIC] CNF Certification FAQ.md

### ISSUE THREAD

**Issue by lixuna** [cncf/cnf-certification#20]
## Short description: 
- Create an CNF that is similar to https://github.com/cncf/k8s-conformance/blob/master/faq.md
- Add an FAQ.md for Frequently Asked Questions about the CNF Certification Program

### Child issues: 
- #40 
- #41
- tbd

**Comment by arieljatib** [comment]
What are some questions to include? 

It would be good to include these on the [program landing page on cncf.io](https://www.cncf.io/certification/cnf/). 

On today's [call w folks at LFN Developer Event](https://wiki.lfnetworking.org/display/LN/2022-06-15+-+Anuket%3A+RA2+Collaborations), @CsatariGergely raised the following good candidates:

1. What is the process for deciding what is on the test? 
2. What is tested? [List of tests](https://github.com/cncf/cnf-certification/blob/main/docs/CNFCertification-1.0-beta.md)
3. What kinds of things are tested?

**Comment by lixuna** [comment]
1. What is the cost of certification?
2. Do I need to re-submit results if we release a new version of our product?
3. Is a participation form required per company or per product?

**Comment by agentpoyo** [comment]
1. What happens if I don't pass enough tests to get certified, who can help us debug or troubleshoot?
2. What is the difference between essential, normal and bonus tests?
3. How does scoring work for passed and failed tests?
4. If passed tests are worth 5 points, why am I seeing a total score end with a 1?
5. How are bonus tests applied in the Certification?

**Comment by lixuna** [comment]
Add to FAQ: 
- how is the CNF Certification Program different from other platform certifications out there? @wavell
